from backend.models.state import AgentState
from backend.agents.memory import save_memory
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import SystemMessage, HumanMessage
import os

def get_llm():
    return ChatGoogleGenerativeAI(model="gemini-2.5-flash", api_key=os.getenv("GEMINI_API_KEY", "dummy"))

async def reflection_node(state: AgentState):
    """
    Evaluates completed work, formats the final message, and saves memory.
    """
    messages = state.get("messages", [])
    user_id = state.get("user_id", "default_user")
    
    command_type = state.get("command_type", "").strip()
    
    context = ""
    if messages and len(messages) > 1:
        # Get the latest message generated by the previous agent node (Study/Productivity/Memory)
        context = messages[-1].content
        
    intent_detected = state.get("intent_detected", "")
    
    if intent_detected == "chat":
        user_msg = messages[0].content if messages else "Hello"
        lower = user_msg.lower().strip()
        
        if "who are you" in lower:
            final_response = "I'm Skillo, your student command center for study planning, Classroom/RAG notes, timetables, deadlines, and focus sessions."
        elif "how are you" in lower or "how r u" in lower:
            final_response = "I'm good, ready to help. Want to work on study planning, RAG notes, timetable, or focus?"
        elif any(w in lower for w in ["hi", "hello", "hey"]):
            final_response = "Hey Gaurav, I'm ready. Want help with study planning, timetable, RAG notes, or focus today?"
        elif any(w in lower for w in ["thanks", "thank you"]):
            final_response = "Anytime. I'm here when you need study, timetable, or RAG help."
        else:
            final_response = "I'm here. You can ask me about study planning, RAG notes, timetable, deadlines, or focus sessions."
        
        log_entry = {
            "node": "Reflection",
            "message": "Generated quick local chat reply. Skipped Gemini and Memory."
        }
        return {
            "messages": [SystemMessage(content=final_response)],
            "reflection_summary": "Small talk.",
            "active_node": "Reflection",
            "pipeline_logs": [log_entry]
        }
        
    if command_type == "weekly_review":
        goals = state.get("active_goals", [])
        system_prompt = f"""
        You are the Reflection Agent acting as a strict but encouraging mentor. 
        The user has requested a Weekly AI Review. Their current active goals are: {goals}
        Review the completed task data and context:
        {context}
        
        Generate a strictly valid JSON response containing the following structure EXACTLY:
        {{
          "score": <an integer from 0 to 100 representing productivity health>,
          "review": "<2 sentence analysis of their week>",
          "recommendation": "<1 actionable improvement>"
        }}
        Do NOT wrap the JSON in markdown code blocks. Just output raw JSON.
        """
        response = await get_llm().ainvoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content="Return the weekly review JSON.")
        ])
        content = response.content.strip()
        # Thoroughly strip markdown blocks
        content = content.replace("```json", "").replace("```", "").strip()
        
        # Save a basic summary for this event
        summary = "User ran the Weekly AI Review."
        await save_memory(user_id=user_id, text=summary, node_type="reflection")
        
        log_entry = {
            "node": "Reflection",
            "message": "Generated structured Weekly AI Review."
        }
        
        return {
            "messages": [SystemMessage(content=content)],
            "reflection_summary": summary,
            "active_node": "Reflection",
            "pipeline_logs": [log_entry]
        }
    
    else:
        system_prompt = f"""
        You are the Reflection Agent. Review the completed task data from the swarm:
        {context}
        
        Synthesize a comprehensive, premium, markdown-formatted final response to the user.
        If the user's input was unclear or a general conversational query, provide a helpful and intelligent response and ask a clarifying question.
        Your response MUST include:
        - A direct answer or synthesis.
        - A recommended next step.
        - 2-3 actionable follow-up suggestions formatted as bullet points.
        
        Simultaneously, generate a 1-sentence summary of what was accomplished to store in long-term memory.
        
        Format your response EXACTLY like this:
        SUMMARY: <your 1-sentence summary>
        ---
        <your final user-facing response in Markdown>
        """
        
        response = await get_llm().ainvoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content="Provide the final synthesized summary.")
        ])
        content = response.content.strip()
        
        summary = "System processed a request."
        final_response = content
        
        if "---" in content:
            parts = content.split("---", 1)
            summary_part = parts[0].strip()
            final_response = parts[1].strip()
            if summary_part.startswith("SUMMARY:"):
                summary = summary_part.replace("SUMMARY:", "").strip()
                
        # Save the summary to pinecone
        await save_memory(user_id=user_id, text=summary, node_type="reflection")
                
        log_entry = {
            "node": "Reflection",
            "message": "Synthesized final data and committed summary to long-term memory."
        }
        
        return {
            "messages": [SystemMessage(content=final_response)],
            "reflection_summary": summary,
            "active_node": "Reflection",
            "pipeline_logs": [log_entry]
        }
